version: 2
project_name: iperf3_exporter

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: "{{ .ProjectName }}-amd64"
    main: ./cmd/iperf3_exporter
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
  - id: "{{ .ProjectName }}-arm64"
    main: ./cmd/iperf3_exporter
    binary: "{{ .ProjectName }}"
    env:
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - "{{ .ProjectName }}-amd64"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --target=goreleaser
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.ref.name={{ .Version }}-amd64
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.documentation=https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md
      - --label=org.opencontainers.image.issues=https://github.com/edgard/{{ .ProjectName }}/issues
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.authors=edgard
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.base.name=alpine:3.21
      - --label=org.opencontainers.image.registry=ghcr.io
      - --label=com.github.package.type=container
      - --label=com.github.package.vcs-ref={{ .FullCommit }}
      - --annotation=org.opencontainers.image.title="{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.description="{{ .ProjectName }} {{ .Version }} {{ .Date }}"
      - --annotation=org.opencontainers.image.created="{{ .Date }}"
      - --annotation=org.opencontainers.image.version="{{ .Version }}"
      - --annotation=org.opencontainers.image.ref.name="{{ .Version }}-amd64"
      - --annotation=org.opencontainers.image.source="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --annotation=org.opencontainers.image.url="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.documentation="https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md"
      - --annotation=org.opencontainers.image.issues="https://github.com/edgard/{{ .ProjectName }}/issues"
      - --annotation=org.opencontainers.image.vendor="edgard"
      - --annotation=org.opencontainers.image.authors="edgard"
      - --annotation=org.opencontainers.image.licenses="Apache-2.0"
      - --annotation=org.opencontainers.image.base.name="alpine:3.21"
      - --annotation=org.opencontainers.image.registry="ghcr.io"
      - --annotation=com.github.package.type="container"
      - --annotation=com.github.package.vcs-ref="{{ .FullCommit }}"

  - use: buildx
    goos: linux
    goarch: arm64
    ids:
      - "{{ .ProjectName }}-arm64"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --target=goreleaser
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }} {{ .Version }} {{ .Date }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.ref.name={{ .Version }}-arm64
      - --label=org.opencontainers.image.source=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.url=https://github.com/edgard/{{ .ProjectName }}
      - --label=org.opencontainers.image.documentation=https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md
      - --label=org.opencontainers.image.issues=https://github.com/edgard/{{ .ProjectName }}/issues
      - --label=org.opencontainers.image.vendor=edgard
      - --label=org.opencontainers.image.authors=edgard
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --label=org.opencontainers.image.base.name=alpine:3.21
      - --label=org.opencontainers.image.registry=ghcr.io
      - --label=com.github.package.type=container
      - --label=com.github.package.vcs-ref={{ .FullCommit }}
      - --annotation=org.opencontainers.image.title="{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.description="{{ .ProjectName }} {{ .Version }} {{ .Date }}"
      - --annotation=org.opencontainers.image.created="{{ .Date }}"
      - --annotation=org.opencontainers.image.version="{{ .Version }}"
      - --annotation=org.opencontainers.image.ref.name="{{ .Version }}-arm64"
      - --annotation=org.opencontainers.image.source="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --annotation=org.opencontainers.image.url="https://github.com/edgard/{{ .ProjectName }}"
      - --annotation=org.opencontainers.image.documentation="https://github.com/edgard/{{ .ProjectName }}/blob/main/README.md"
      - --annotation=org.opencontainers.image.issues="https://github.com/edgard/{{ .ProjectName }}/issues"
      - --annotation=org.opencontainers.image.vendor="edgard"
      - --annotation=org.opencontainers.image.authors="edgard"
      - --annotation=org.opencontainers.image.licenses="Apache-2.0"
      - --annotation=org.opencontainers.image.base.name="alpine:3.21"
      - --annotation=org.opencontainers.image.registry="ghcr.io"
      - --annotation=com.github.package.type="container"
      - --annotation=com.github.package.vcs-ref="{{ .FullCommit }}"

docker_manifests:
  - name_template: ghcr.io/edgard/iperf3_exporter:{{ .Version }}
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-amd64
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/iperf3_exporter:{{ .Major }}
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-amd64
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/iperf3_exporter:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-amd64
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-arm64

  - name_template: ghcr.io/edgard/iperf3_exporter:latest
    image_templates:
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-amd64
      - ghcr.io/edgard/iperf3_exporter:{{ .Version }}-arm64

release:
  github:
    owner: edgard
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  header: |
    ## {{ .ProjectName }} {{ .Version }} ({{ .Date }})

    This release was automatically generated by GitHub Actions.

changelog:
  sort: asc
  use: github
  groups:
    - title: Breaking Changes
      regexp: "^.*?(feat|fix|build|chore|ci|docs|style|refactor|perf|test)(\\([[:word:]]+\\))?!:.+$"
      order: 0
    - title: Features
      regexp: "^.*?feat(\\([[:word:]]+\\))?:.+$"
      order: 1
    - title: Bug Fixes
      regexp: "^.*?fix(\\([[:word:]]+\\))?:.+$"
      order: 2
    - title: Performance Improvements
      regexp: "^.*?perf(\\([[:word:]]+\\))?:.+$"
      order: 3
    - title: Refactoring
      regexp: "^.*?refactor(\\([[:word:]]+\\))?:.+$"
      order: 4
    - title: Code Style
      regexp: "^.*?style(\\([[:word:]]+\\))?:.+$"
      order: 5
    - title: Documentation
      regexp: "^.*?docs(\\([[:word:]]+\\))?:.+$"
      order: 6
    - title: Tests
      regexp: "^.*?test(\\([[:word:]]+\\))?:.+$"
      order: 7
    - title: Build System
      regexp: "^.*?build(\\([[:word:]]+\\))?:.+$"
      order: 8
    - title: CI
      regexp: "^.*?ci(\\([[:word:]]+\\))?:.+$"
      order: 9
    - title: Chores
      regexp: "^.*?chore(\\([[:word:]]+\\))?:.+$"
      order: 10
    - title: Reverts
      regexp: "^.*?revert(\\([[:word:]]+\\))?:.+$"
      order: 11
    - title: Others
      order: 999
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"
      - "^Merge remote"
