env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - openbsd
      - netbsd
      - darwin
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - -s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate="{{.Date}}" -X github.com/prometheus/common/version.Branch={{.Tag}} -X github.com/prometheus/common/version.Revision={{.FullCommit}} -X github.com/prometheus/common/version.BuildUser="{{.Env.USER}}"

archives:
  -
    name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - NOTICE

checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

dockers:
  -
    goos: linux
    goarch: amd64

    image_templates:
      - 'edgard/iperf3-exporter:{{ .Tag }}'
      - 'edgard/iperf3-exporter:latest'

    build_flag_templates:
    - '--label=org.label-schema.schema-version=1.0'
    - '--label=org.label-schema.version={{.Version}}'
    - '--label=org.label-schema.name={{.ProjectName}}'
